/**
 * Application Version and Build Metadata
 * photo.emre.xyz
 *
 * Auto-generated by scripts/sync-version.mjs
 * DO NOT EDIT MANUALLY - Update package.json or use 'make version-*' instead.
 */

export const APP_NAME = "photo-emre-xyz" as const;
export const APP_VERSION = "0.1.0" as const;
export const APP_DESCRIPTION = "Sovereign, decentralized event photo album platform built on Nostr and Blossom" as const;
export const APP_LICENSE = "MIT" as const;
export const APP_REPOSITORY = "https://github.com/delirehberi/photo.emre.xyz" as const;

export interface AppBuildInfo {
  name: string;
  version: string;
  description: string;
  license: string;
  repository: string;
  releaseDate: string;
}

export const APP_BUILD_INFO: AppBuildInfo = {
  name: APP_NAME,
  version: APP_VERSION,
  description: APP_DESCRIPTION,
  license: APP_LICENSE,
  repository: APP_REPOSITORY,
  releaseDate: "2026-09-17",
};
