#!/usr/bin/env node
/**
 * scripts/sync-version.mjs
 *
 * Synchronizes version information from package.json into src/lib/version.ts
 * ensuring a single source of truth for runtime SSR/client exports.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = resolve(__dirname, '..');

const pkgPath = resolve(rootDir, 'package.json');
const targetPath = resolve(rootDir, 'src/lib/version.ts');

if (!existsSync(pkgPath)) {
  console.error(`Error: package.json not found at ${pkgPath}`);
  process.exit(1);
}

const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
const version = pkg.version || '0.1.0';
const appName = pkg.name || 'photo-emre-xyz';
const appDescription =
  pkg.description ||
  'Sovereign, decentralized event photo album platform built on Nostr and Blossom';
const license = pkg.license || 'MIT';
const repository =
  (typeof pkg.repository === 'string' ? pkg.repository : pkg.repository?.url) ||
  'https://github.com/delirehberi/photo.emre.xyz';

const content = `/**
 * Application Version and Build Metadata
 * photo.emre.xyz
 *
 * Auto-generated by scripts/sync-version.mjs
 * DO NOT EDIT MANUALLY - Update package.json or use 'make version-*' instead.
 */

export const APP_NAME = ${JSON.stringify(appName)} as const;
export const APP_VERSION = ${JSON.stringify(version)} as const;
export const APP_DESCRIPTION = ${JSON.stringify(appDescription)} as const;
export const APP_LICENSE = ${JSON.stringify(license)} as const;
export const APP_REPOSITORY = ${JSON.stringify(repository)} as const;

export interface AppBuildInfo {
  name: string;
  version: string;
  description: string;
  license: string;
  repository: string;
  releaseDate: string;
}

export const APP_BUILD_INFO: AppBuildInfo = {
  name: APP_NAME,
  version: APP_VERSION,
  description: APP_DESCRIPTION,
  license: APP_LICENSE,
  repository: APP_REPOSITORY,
  releaseDate: ${JSON.stringify(new Date().toISOString().split('T')[0])},
};
`;

writeFileSync(targetPath, content, 'utf-8');
console.log(`✓ Synchronized version ${version} to src/lib/version.ts`);
